import {useEffect,useMemo,useState} from 'react';
import {Plus,RefreshCw,WalletCards} from 'lucide-react';
import {insertRow,rows} from '../lib/api';
import Modal from '../components/Modal';

type Student={id:string;student_code:string;full_name:string;status?:string};
type Fee={id:string;student_id:string;month:string;amount:number;discount:number;fine:number;paid:number;due_date?:string|null;status:string};
type Payment={id:string;fee_id:string;amount:number;payment_date:string;method:string;receipt_no?:string|null};
const money=(v:number)=>`₨${Number(v||0).toLocaleString('en-PK',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
const totalFor=(f:Fee)=>Math.max(0,Number(f.amount||0)-Number(f.discount||0)+Number(f.fine||0));

export default function FeePayments({readOnly=false}:{readOnly?:boolean}){
 const [fees,setFees]=useState<Fee[]>([]),[students,setStudents]=useState<Student[]>([]),[payments,setPayments]=useState<Payment[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[search,setSearch]=useState('');
 const [studentId,setStudentId]=useState(''),[feeId,setFeeId]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [f,s,p]=await Promise.all([rows('fees','*','created_at',false),rows('students','id,student_code,full_name,status','full_name',true),rows('fee_payments','*','payment_date',false)]);setFees(f as Fee[]);setStudents((s as Student[]).filter(x=>x.status!=='inactive'));setPayments(p as Payment[])}catch(e:any){setError([e?.message,e?.details,e?.hint].filter(Boolean).join(' | ')||'Unable to load payment records.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const studentMap=useMemo(()=>Object.fromEntries(students.map(s=>[s.id,s])),[students]);
 const paidMap=useMemo(()=>{const m:Record<string,number>={};for(const p of payments)m[p.fee_id]=(m[p.fee_id]||0)+Number(p.amount||0);for(const f of fees)if(!(f.id in m))m[f.id]=Number(f.paid||0);return m},[payments,fees]);
 const availableFees=useMemo(()=>fees.filter(f=>f.student_id===studentId && Math.max(0,totalFor(f)-(paidMap[f.id]??Number(f.paid||0)))>0),[fees,studentId,paidMap]);
 const paymentRows=useMemo(()=>payments.map(p=>({p,student:studentMap[fees.find(f=>f.id===p.fee_id)?.student_id||''],fee:fees.find(f=>f.id===p.fee_id)})).filter(x=>`${x.student?.full_name||''} ${x.student?.student_code||''} ${x.fee?.month||''} ${x.p.receipt_no||''} ${x.p.method||''}`.toLowerCase().includes(search.toLowerCase())),[payments,fees,studentMap,search]);
 const reset=()=>{setStudentId('');setFeeId('')};
 const save=async(e:any)=>{e.preventDefault();if(saving)return;if(!feeId){setError('Select the student fee you want to receive a payment for.');return}const fee=fees.find(f=>f.id===feeId);if(!fee){setError('The selected fee could not be found. Refresh and try again.');return}const fd=new FormData(e.currentTarget);const amount=Number(fd.get('amount'))||0;const remaining=Math.max(0,totalFor(fee)-(paidMap[fee.id]??Number(fee.paid||0)));if(amount<=0){setError('Enter a payment amount greater than 0.');return}if(amount>remaining){setError(`Payment cannot exceed the remaining balance of ${money(remaining)}.`);return}setSaving(true);setError('');try{await insertRow('fee_payments',{fee_id:fee.id,amount,payment_date:String(fd.get('payment_date')||new Date().toISOString().slice(0,10)),method:String(fd.get('method')||'cash'),receipt_no:String(fd.get('receipt_no')||'').trim()||`RCPT-${Date.now().toString().slice(-8)}`});setOpen(false);reset();await load()}catch(e:any){setError([e?.message,e?.details,e?.hint,e?.code].filter(Boolean).join(' | ')||'Unable to record the payment.')}finally{setSaving(false)}};
 return <section className="page fees-page"><div className="page-head"><div><span className="eyebrow dark-eyebrow">FINANCE</span><h2>Fee Payments</h2><p>Record and review student payments.</p></div>{!readOnly&&<button className="primary" onClick={()=>{setError('');reset();setOpen(true)}}><Plus size={17}/> Add payment</button>}</div>{error&&<div className="notice error"><b>Something needs attention</b><span>{error}</span></div>}
 <div className="toolbar finance-toolbar"><input placeholder="Search student, ID, month or receipt…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
 <div className="table-card"><div className="table-card-head"><div><h3>Payment records</h3><p>Student names are shown instead of internal fee IDs.</p></div><WalletCards size={20}/></div><div className="table-wrap">{loading?<div className="empty">Loading payment records…</div>:paymentRows.length===0?<div className="empty">No payment records found.</div>:<table><thead><tr><th>Student</th><th>Fee month</th><th>Amount</th><th>Payment date</th><th>Method</th><th>Receipt</th></tr></thead><tbody>{paymentRows.map(({p,student,fee})=><tr key={p.id}><td><b>{student?.full_name||'Unknown student'}</b><small>{student?.student_code||'—'}</small></td><td>{fee?.month||'—'}</td><td><b>{money(p.amount)}</b></td><td>{p.payment_date||'—'}</td><td>{String(p.method||'cash').replace(/^./,x=>x.toUpperCase())}</td><td>{p.receipt_no||'—'}</td></tr>)}</tbody></table>}</div></div>
 {open&&!readOnly&&<Modal title="Add Fee Payment" onClose={()=>{setOpen(false);reset()}}><form className="form-grid" onSubmit={save}><label>Student *<select value={studentId} onChange={e=>{setStudentId(e.target.value);setFeeId('')}} required><option value="">Select student…</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name} — {s.student_code}</option>)}</select></label><label>Fee *<select value={feeId} onChange={e=>setFeeId(e.target.value)} disabled={!studentId} required><option value="">{studentId?'Select fee…':'Select a student first'}</option>{availableFees.map(f=><option key={f.id} value={f.id}>{f.month} — Remaining {money(Math.max(0,totalFor(f)-(paidMap[f.id]??Number(f.paid||0))))}</option>)}</select></label>{feeId&&<div className="payment-summary"><span>Student</span><b>{studentMap[studentId]?.full_name}</b></div>}<label>Payment amount *<input name="amount" type="number" min="0.01" step="0.01" max={feeId?Math.max(0,totalFor(fees.find(f=>f.id===feeId)!)-(paidMap[feeId]??0)):undefined} required/></label><label>Payment date<input name="payment_date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Method<select name="method" defaultValue="cash"><option value="cash">Cash</option><option value="bank">Bank</option><option value="card">Card</option><option value="online">Online</option></select></label><label>Receipt no.<input name="receipt_no" placeholder="Auto-generated if empty"/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>{setOpen(false);reset()}}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save payment'}</button></div></form></Modal>}
 </section>
}
