import {useEffect,useMemo,useState} from 'react';
import {Plus,RefreshCw,ReceiptText,WalletCards} from 'lucide-react';
import {rows,insertRow,updateRow,deleteRow} from '../lib/api';
import Modal from '../components/Modal';

type Student={id:string;student_code:string;full_name:string;status?:string};
type Fee={id:string;student_id:string;month:string;amount:number;discount:number;fine:number;paid:number;due_date?:string|null;status:string};
type Payment={id:string;fee_id:string;amount:number;payment_date:string;method:string;receipt_no?:string|null};
const money=(v:number)=>`₨${Number(v||0).toLocaleString('en-PK',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
const totalFor=(f:Fee)=>Math.max(0,Number(f.amount||0)-Number(f.discount||0)+Number(f.fine||0));
const statusFor=(f:Fee,paid:number)=>{const total=totalFor(f);if(paid<=0)return 'unpaid';if(paid>=total)return 'paid';return 'partial'};

export default function Fees({admin=false}:{admin?:boolean}){
 const [fees,setFees]=useState<Fee[]>([]),[students,setStudents]=useState<Student[]>([]),[payments,setPayments]=useState<Payment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[paymentOpen,setPaymentOpen]=useState<Fee|null>(null),[editing,setEditing]=useState<Fee|null>(null),[search,setSearch]=useState(''),[saving,setSaving]=useState(false);
 const [studentId,setStudentId]=useState(''),[month,setMonth]=useState(new Date().toISOString().slice(0,10)),[amount,setAmount]=useState(''),[discount,setDiscount]=useState('0'),[fine,setFine]=useState('0'),[dueDate,setDueDate]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [f,s,p]=await Promise.all([rows('fees','*','created_at',false),rows('students','*','full_name',true),rows('fee_payments','*','payment_date',false).catch(()=>[])]);setFees(f as Fee[]);setStudents((s as Student[]).filter(x=>x.status!=='inactive'));setPayments(p as Payment[])}catch(e:any){setError(e?.message||'Unable to load fee records.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const studentMap=useMemo(()=>Object.fromEntries(students.map(s=>[s.id,s])),[students]);
 const paidMap=useMemo(()=>{const m:Record<string,number>={};for(const p of payments)m[p.fee_id]=(m[p.fee_id]||0)+Number(p.amount||0);for(const f of fees)if(!(f.id in m))m[f.id]=Number(f.paid||0);return m},[payments,fees]);
 const normalized=useMemo(()=>fees.map(f=>({...f,paid:paidMap[f.id]??Number(f.paid||0),status:statusFor(f,paidMap[f.id]??Number(f.paid||0))})),[fees,paidMap]);
 const filtered=normalized.filter(f=>{const s=studentMap[f.student_id];return `${s?.full_name||''} ${s?.student_code||''} ${f.month} ${f.status}`.toLowerCase().includes(search.toLowerCase())});
 const reset=()=>{setStudentId('');setMonth(new Date().toISOString().slice(0,10));setAmount('');setDiscount('0');setFine('0');setDueDate('');setEditing(null)};
 const openAdd=()=>{setError('');reset();setOpen(true)};
 const openEdit=(fee:Fee)=>{setError('');setEditing(fee);setStudentId(fee.student_id);setMonth(fee.month);setAmount(String(fee.amount||0));setDiscount(String(fee.discount||0));setFine(String(fee.fine||0));setDueDate(fee.due_date||'');setOpen(true)};
 const saveFee=async(e:any)=>{e.preventDefault();if(saving)return;if(!studentId||!amount){setError('Student and fee amount are required.');return}const a=Number(amount)||0,d=Number(discount)||0,f=Number(fine)||0;if(a<0||d<0||f<0){setError('Amounts cannot be negative.');return}if(!editing&&fees.some(x=>x.student_id===studentId&&x.month===month)){setError('A fee record already exists for this student and month.');return}setSaving(true);setError('');try{const existingPaid=editing?paidMap[editing.id]??Number(editing.paid||0):0;const p={student_id:studentId,month,due_date:dueDate||null,amount:a,discount:d,fine:f,paid:existingPaid,status:statusFor({amount:a,discount:d,fine:f} as Fee,existingPaid)};if(editing)await updateRow('fees',editing.id,p);else await insertRow('fees',p);setOpen(false);reset();await load()}catch(e:any){setError([e?.message,e?.details,e?.hint].filter(Boolean).join(' | ')||'Unable to save the fee record.')}finally{setSaving(false)}};
 const recordPayment=async(e:any)=>{e.preventDefault();if(!paymentOpen||saving)return;const fd=new FormData(e.currentTarget);const pay=Number(fd.get('amount'))||0;const current=paidMap[paymentOpen.id]??Number(paymentOpen.paid||0);const total=totalFor(paymentOpen);if(pay<=0){setError('Enter a payment amount greater than 0.');return}if(current+pay>total){setError(`Payment cannot exceed the remaining balance of ${money(Math.max(0,total-current))}.`);return}setSaving(true);setError('');try{await insertRow('fee_payments',{fee_id:paymentOpen.id,amount:pay,payment_date:String(fd.get('payment_date')||new Date().toISOString().slice(0,10)),method:String(fd.get('method')||'cash'),receipt_no:String(fd.get('receipt_no')||'').trim()||`RCPT-${Date.now().toString().slice(-8)}`});setPaymentOpen(null);await load()}catch(e:any){setError([e?.message,e?.details,e?.hint].filter(Boolean).join(' | ')||'Unable to record the payment.')}finally{setSaving(false)}};
 const billed=filtered.reduce((n,f)=>n+totalFor(f),0),paid=filtered.reduce((n,f)=>n+Number(f.paid||0),0),outstanding=filtered.reduce((n,f)=>n+Math.max(0,totalFor(f)-Number(f.paid||0)),0);
 return <section className="page fees-page"><div className="page-head"><div><span className="eyebrow dark-eyebrow">FINANCE</span><h2>Fees & Payments</h2><p>Fee records, payments and balances.</p></div>{admin&&<button className="primary" onClick={openAdd}><Plus size={17}/> Add fee</button>}</div>{error&&<div className="notice error"><b>Something needs attention</b><span>{error}</span></div>}
 <div className="toolbar finance-toolbar"><input placeholder="Search student, ID or status…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
 <div className="card-grid finance-stats"><div className="card"><small>Total billed</small><div className="big-number">{money(billed)}</div></div><div className="card"><small>Total paid</small><div className="big-number">{money(paid)}</div></div><div className="card"><small>Outstanding</small><div className="big-number">{money(outstanding)}</div></div><div className="card"><small>Records</small><div className="big-number">{filtered.length}</div></div></div>
 <div className="table-card"><div className="table-card-head"><div><h3>Fee records</h3><p>Current balances and payment status.</p></div><ReceiptText size={20}/></div><div className="table-wrap">{loading?<div className="empty">Loading fee records…</div>:filtered.length===0?<div className="empty">No fee records found.</div>:<table><thead><tr><th>Student</th><th>Month</th><th>Total</th><th>Paid</th><th>Remaining</th><th>Due date</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(f=>{const s=studentMap[f.student_id],total=totalFor(f),rem=Math.max(0,total-Number(f.paid||0));return <tr key={f.id}><td><b>{s?.full_name||'Unknown student'}</b><small>{s?.student_code||'—'}</small></td><td>{f.month}</td><td>{money(total)}</td><td>{money(Number(f.paid||0))}</td><td>{money(rem)}</td><td>{f.due_date||'—'}</td><td><span className={`status-pill ${f.status}`}>{f.status==='paid'?'Paid':f.status==='partial'?'Partial':'Unpaid'}</span></td><td><div className="row-actions">{rem>0?<button className="link-btn" onClick={()=>{setError('');setPaymentOpen(f)}}><WalletCards size={14}/> Record payment</button>:<span className="muted">Paid in full</span>}{admin&&<><button className="link-btn" onClick={()=>openEdit(f)}>Edit</button><button className="danger-link" onClick={async()=>{if(confirm('Delete this fee record?')){try{await deleteRow('fees',f.id);await load()}catch(e:any){setError(e?.message||String(e))}}}}>Delete</button></>}</div></td></tr>})}</tbody></table>}</div></div>
 {open&&admin&&<Modal title={editing?'Edit Fee':'Add Monthly Fee'} onClose={()=>{setOpen(false);reset()}}><form className="form-grid" onSubmit={saveFee}><label>Student *<select value={studentId} onChange={e=>setStudentId(e.target.value)} required><option value="">Select student…</option>{students.map(s=><option value={s.id} key={s.id}>{s.student_code} — {s.full_name}</option>)}</select></label><label>Fee month *<input type="date" value={month} onChange={e=>setMonth(e.target.value)} required/></label><label>Fee amount *<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Discount<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label>Fine<input type="number" min="0" step="0.01" value={fine} onChange={e=>setFine(e.target.value)}/></label><label>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>{setOpen(false);reset()}}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':editing?'Update fee':'Save fee'}</button></div></form></Modal>}
 {paymentOpen&&<Modal title={`Record Payment — ${studentMap[paymentOpen.student_id]?.full_name||'Student'}`} onClose={()=>setPaymentOpen(null)}><div className="payment-summary"><span>Remaining balance</span><b>{money(Math.max(0,totalFor(paymentOpen)-(paidMap[paymentOpen.id]??Number(paymentOpen.paid||0))))}</b></div><form className="form-grid" onSubmit={recordPayment}><label>Payment amount *<input name="amount" type="number" min="0.01" step="0.01" max={Math.max(0,totalFor(paymentOpen)-(paidMap[paymentOpen.id]??Number(paymentOpen.paid||0)))} required/></label><label>Payment date<input name="payment_date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Method<select name="method" defaultValue="cash"><option value="cash">Cash</option><option value="bank">Bank</option><option value="card">Card</option><option value="online">Online</option></select></label><label>Receipt no.<input name="receipt_no" placeholder="Auto-generated if empty"/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setPaymentOpen(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save payment'}</button></div></form></Modal>}
 </section>
}
