import {useEffect,useState} from 'react';
import {rows,insertRow,updateRow,deleteRow} from '../lib/api';
import Modal from '../components/Modal';

export default function Submissions({teacher=false,admin=false}:{teacher?:boolean;admin?:boolean}){
 const [assignments,setAssignments]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [a,s,x]=await Promise.all([rows('assignments','id,title,class_name,due_date','title',true),rows('students','id,full_name,student_code,class_name','full_name',true),rows('assignment_submissions','*','submitted_at',false)]);setAssignments(a);setStudents(s);setItems(x);setError('')}catch(e:any){setError(e.message||String(e))}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const save=async(e:any)=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);const assignmentId=String(f.get('assignment_id')||'').trim(),studentId=String(f.get('student_id')||'').trim();if(!assignmentId){setError('Please select an assignment first.');return}if(!studentId){setError('Please select a student first.');return}const p={assignment_id:assignmentId,student_id:studentId,submitted_at:String(f.get('submitted_at')||'')||null,marks:f.get('marks')?Number(f.get('marks')):null,feedback:String(f.get('feedback')||'').trim()||null,status:String(f.get('status')||'pending')};try{const existing=items.find(x=>x.assignment_id===p.assignment_id&&x.student_id===p.student_id);if(existing){setError('This submission has already been recorded and is locked.');return}await insertRow('assignment_submissions',p);setOpen(false);await load()}catch(e:any){setError(e.message||String(e))}};
 const openForm=()=>{setError('');if(assignments.length===0){setError('No assignments are available. Create an assignment first.');return}if(students.length===0){setError('No students are available. Add a student first.');return}setOpen(true)};
 return <section className="page"><div className="page-head"><div><h2>Assignment Submissions</h2><p>{teacher&&!admin?'Record each submission once; saved submissions cannot be edited.':'Track student submissions, marks and feedback.'}</p></div>{(admin||teacher)&&<button className="primary" onClick={openForm}>＋ Record Submission</button>}</div><div className="toolbar"><button className="secondary" onClick={load}>↻ Refresh</button></div>{error&&<div className="alert">{error}</div>}<div className="table-wrap">{loading?<div className="empty">Loading…</div>:items.length===0?<div className="empty">No submissions found.</div>:<table><thead><tr><th>Assignment</th><th>Student</th><th>Submitted</th><th>Marks</th><th>Status</th><th>Feedback</th><th>Record</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{assignments.find(a=>a.id===x.assignment_id)?.title||'—'}</td><td>{students.find(s=>s.id===x.student_id)?.full_name||'—'}</td><td>{x.submitted_at?new Date(x.submitted_at).toLocaleString():'—'}</td><td>{x.marks??'—'}</td><td>{x.status||'pending'}</td><td>{x.feedback||'—'}</td><td>{admin?<><button className="link-btn" onClick={()=>{}}>View</button><button className="danger-link" onClick={async()=>{if(confirm('Delete this submission?')){try{await deleteRow('assignment_submissions',x.id);load()}catch(e:any){setError(e.message)}}}}>Delete</button></>:<span className="status">Locked</span>}</td></tr>)}</tbody></table>}</div>{open&&<Modal title="Record Submission" onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={save}><label>Assignment *<select name="assignment_id" defaultValue="" required><option value="">Select assignment</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.title}{a.class_name?` — ${a.class_name}`:''}{a.due_date?` · Due ${a.due_date}`:''}</option>)}</select></label><label>Student *<select name="student_id" defaultValue="" required><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name} ({s.student_code}){s.class_name?` — ${s.class_name}`:''}</option>)}</select></label><label>Submitted At<input name="submitted_at" type="datetime-local"/></label><label>Marks<input name="marks" type="number" min="0" step="0.01"/></label><label>Status<select name="status" defaultValue="submitted"><option value="pending">Pending</option><option value="submitted">Submitted</option><option value="late">Late</option><option value="graded">Graded</option></select></label><label>Feedback<textarea name="feedback" rows={4}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Save Submission</button></div></form></Modal>}</section>
}
