import {useEffect,useState} from 'react';
import {CalendarClock,ChevronRight,Plus,RefreshCw,X} from 'lucide-react';
import {rows,insertRow,updateRow,deleteRow} from '../lib/api';
import Modal from '../components/Modal';
export default function Teachers({readOnly=false}:{readOnly?:boolean}){
 const [data,setData]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[slots,setSlots]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState<any|null>(null),[search,setSearch]=useState(''),[profile,setProfile]=useState<any|null>(null);
 const load=async()=>{setLoading(true);setError('');try{const t=await rows('teachers','*','created_at',false);setData(t);const [c,s,p]=await Promise.all([rows('classes','*','name',true).catch(()=>[]),rows('class_timetable','*','period_no',true).catch(()=>[]),rows('profiles','id,full_name,role','full_name',true).catch(()=>[])]);setClasses(c);setSlots(s);setProfiles(p.filter((x:any)=>x.role==='teacher'));}catch(e:any){setError(e?.message||'Unable to load teachers. Check the database setup and connection.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const save=async(e:any)=>{e.preventDefault();if(saving)return;setError('');setSaving(true);const fd=new FormData(e.currentTarget);const p={employee_code:String(fd.get('employee_code')||'').trim(),full_name:String(fd.get('full_name')||'').trim(),phone:String(fd.get('phone')||'').trim()||null,email:String(fd.get('email')||'').trim()||null,subject:String(fd.get('subject')||'').trim()||null,status:String(fd.get('status')||'active'),profile_id:String(fd.get('profile_id')||'').trim()||null};if(!p.employee_code||!p.full_name){setError('Employee ID and Name are required.');return}try{if(editing)await updateRow('teachers',editing.id,p);else await insertRow('teachers',p);setOpen(false);setEditing(null);await load()}catch(e:any){const msg=[e?.message,e?.details,e?.hint,e?.code].filter(Boolean).join(' | ');setError(msg.includes('duplicate key')||msg.includes('employee_code')?'That Employee ID is already in use. Please enter a different ID.':msg||'Unable to save teacher. Please try again.')}finally{setSaving(false)}};
 const filtered=data.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
 const openProfile=(t:any)=>{const teaching=slots.filter(s=>s.teacher_id===t.id).map(s=>({...s,classRow:classes.find(c=>c.id===s.class_id)}));setProfile({...t,teaching})};
 return <section className="page"><div className="page-head"><div><span className="eyebrow dark-eyebrow">FACULTY</span><h2>Teachers</h2><p>Faculty records and teaching information.</p></div>{!readOnly&&<button className="primary" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/> Add teacher</button>}</div>{error&&<div className="notice error">{error}</div>}
 <div className="panel"><div className="panel-title"><div><b>Teachers</b><span className="muted">{filtered.length} records</span></div><input className="toolbar-search" placeholder="Search teachers…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
 {loading?<div className="empty">Loading…</div>:filtered.length===0?<div className="empty">No teachers found.</div>:<div className="table-wrap"><table><thead><tr><th>Employee ID</th><th>Name</th><th>Subject</th><th>Phone</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="clickable-row" onClick={()=>openProfile(r)}><td>{r.employee_code||'—'}</td><td><b>{r.full_name}</b></td><td>{r.subject||'—'}</td><td>{r.phone||'—'}</td><td>{r.status||'active'}</td><td><ChevronRight size={16}/>{!readOnly&&<><button className="link-btn" onClick={e=>{e.stopPropagation();setEditing(r);setOpen(true)}}>Edit</button><button className="danger-link" onClick={async e=>{e.stopPropagation();if(confirm('Delete this teacher?')){try{await deleteRow('teachers',r.id);load()}catch(x:any){setError(x?.message||String(x))}}}}>Delete</button></>}</td></tr>)}</tbody></table></div>}</div>
 {open&&<Modal title={editing?'Edit Teacher':'Add Teacher'} onClose={()=>{setOpen(false);setEditing(null)}}><form className="form-grid" onSubmit={save}><label>Employee ID *<input name="employee_code" defaultValue={editing?.employee_code??''} required/></label><label>Name *<input name="full_name" defaultValue={editing?.full_name??''} required/></label><label>Phone<input name="phone" defaultValue={editing?.phone??''}/></label><label>Email<input name="email" type="email" defaultValue={editing?.email??''}/></label><label>Main subject (optional)<input name="subject" defaultValue={editing?.subject??''} placeholder="e.g. Mathematics"/></label><label>Login account (optional)<select name="profile_id" defaultValue={editing?.profile_id??''}><option value="">Not linked</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><label>Status<select name="status" defaultValue={editing?.status??'active'}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save teacher'}</button></div></form></Modal>}
 {profile&&<div className="student-modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setProfile(null)}}><div className="teacher-profile-modal"><div className="student-profile-head"><div className="profile-avatar">{profile.full_name?.slice(0,1)||'T'}</div><div><span className="eyebrow dark-eyebrow">TEACHER PROFILE</span><h2>{profile.full_name}</h2><p>{profile.employee_code} · {profile.subject||'Faculty member'}</p></div><button className="icon-button" onClick={()=>setProfile(null)}><X size={19}/></button></div><div className="teacher-profile-grid"><section><h3>Teacher information</h3><p><b>Phone:</b> {profile.phone||'—'}</p><p><b>Email:</b> {profile.email||'—'}</p><p><b>Status:</b> {profile.status||'active'}</p></section><section><h3>Assigned classes</h3><div className="profile-history">{classes.filter(c=>c.class_teacher_id===profile.id).map(c=><span className="history-chip" key={c.id}>{c.name} · Class teacher</span>)}{!classes.some(c=>c.class_teacher_id===profile.id)&&<span className="muted">No class-teacher assignment.</span>}</div></section><section className="teacher-schedule"><h3><CalendarClock size={17}/> My timetable</h3><div className="table-wrap"><table><thead><tr><th>Period</th><th>Time</th><th>Class</th><th>Subject</th></tr></thead><tbody>{profile.teaching.length?profile.teaching.map((s:any)=><tr key={s.id||`${s.class_id}-${s.period_no}`}><td>P{s.period_no}</td><td>{s.start_time}–{s.end_time}</td><td>{s.classRow?s.classRow.name:'—'}</td><td>{s.subject}</td></tr>):<tr><td colSpan={4}>No timetable entries.</td></tr>}</tbody></table></div></section></div></div></div>}
 </section>
}
