import {useEffect,useState} from 'react'; import {rows,insertRow,updateRow,deleteRow} from '../lib/api'; import Modal from './Modal';
export type Field={key:string,label:string,type?:string,required?:boolean,options?:string[]};
export default function CrudPage({title,table,fields,select='*',order='created_at',readOnly=false,canAdd=false}:{title:string;table:string;fields:Field[];select?:string;order?:string;readOnly?:boolean;canAdd?:boolean}){
 const [data,setData]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState<any|null>(null),[search,setSearch]=useState('');
 const load=async()=>{setLoading(true);try{setData(await rows(table,select,order,false));setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const save=async(e:any)=>{e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const p:any={};fields.forEach(f=>{const v=fd.get(f.key);if(v===''){p[f.key]=(f.key==='status'&&(table==='students'||table==='teachers'))?'active':null}else p[f.key]=v});try{editing?await updateRow(table,editing.id,p):await insertRow(table,p);setOpen(false);setEditing(null);load()}catch(e:any){console.error('EduSphere save error:',e);const msg=[e?.message,e?.details,e?.hint,e?.code].filter(Boolean).join(' | ');setError('Save failed: '+(msg||String(e)))}};
 const filtered=data.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
 return <section className="page"><div className="page-head"><div><h2>{title}</h2><p>Manage {title.toLowerCase()} with shared cloud data.</p></div>{(!readOnly||canAdd)&&<button className="primary" onClick={()=>{setEditing(null);setOpen(true)}}>＋ Add</button>}</div><div className="toolbar"><input placeholder={'Search '+title.toLowerCase()+'...'} value={search} onChange={e=>setSearch(e.target.value)}/><button className="secondary" onClick={load}>↻ Refresh</button></div>{error&&<div className="alert"><strong>{error}</strong><div className="muted">Open the browser Console (F12 → Console) if you need the full database error.</div></div>}<div className="table-wrap">{loading?<div className="empty">Loading…</div>:filtered.length===0?<div className="empty">No records found.</div>:<table><thead><tr>{fields.map(f=><th key={f.key}>{f.label}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{fields.map(f=><td key={f.key}>{r[f.key] ?? '—'}</td>)}<td>{!readOnly&&<button className="link-btn" onClick={()=>{setEditing(r);setOpen(true)}}>Edit</button>}{!readOnly&&<button className="danger-link" onClick={async()=>{if(confirm('Delete this record?')){await deleteRow(table,r.id);load()}}}>Delete</button>}</td></tr>)}</tbody></table>}</div>{open&&<Modal title={editing?'Edit '+title:'Add '+title} onClose={()=>{setOpen(false);setEditing(null)}}><form className="form-grid" onSubmit={save}>{fields.map(f=><label key={f.key}>{f.label}{f.required&&' *'}{f.options?<select name={f.key} defaultValue={editing?.[f.key]??''} required={f.required}><option value="">Select…</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:<input name={f.key} type={f.type||'text'} defaultValue={editing?.[f.key]??''} required={f.required}/>}</label>)}<div className="form-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Save</button></div></form></Modal>}</section>
}
