import {useEffect,useState} from 'react';
import Sidebar from './components/Sidebar'; import Header from './components/Header'; import Dashboard from './pages/Dashboard'; import CrudPage from './components/CrudPage'; import Attendance from './pages/Attendance'; import Teachers from './pages/Teachers'; import Login from './pages/Login'; import Fees from './pages/Fees'; import Assignments from './pages/Assignments'; import Submissions from './pages/Submissions'; import {supabase} from './lib/supabase'; import {getProfile} from './lib/api'; import './styles.css'; import Landing from './pages/Landing'; import ActivityLog from './pages/ActivityLog'; import Results from './pages/Results'; import Students from './pages/Students';
const pages:any={Students:{table:'students',fields:[['student_code','Student ID'],['full_name','Name'],['gender','Gender'],['date_of_birth','DOB','date'],['phone','Phone'],['email','Email'],['class_name','Class'],['section','Section'],['roll_no','Roll No'],['parent_name','Parent/Guardian'],['parent_phone','Parent Phone'],['status','Status']]},Classes:{table:'classes',order:'',fields:[['name','Class'],['section','Section'],['academic_year','Academic Year']]},Exams:{table:'exams',fields:[['name','Exam Name'],['exam_date','Date','date'],['academic_year','Academic Year'],['term','Term']]},Notices:{table:'notices',fields:[['title','Title'],['body','Message'],['publish_at','Publish At','datetime-local'],['expires_at','Expires At','datetime-local']]},'Fee Payments':{table:'fee_payments',fields:[['fee_id','Fee ID'],['amount','Amount','number'],['payment_date','Payment Date','date'],['method','Method'],['receipt_no','Receipt No']]}};
const teacherWrite=new Set(['Student Attendance','Teacher Attendance','Fees','Fee Payments','Assignments','Assignment Submissions','Exams','Results','Notices']);
function App(){const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[active,setActive]=useState('Dashboard'),[checking,setChecking]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session){try{setProfile(await getProfile())}catch{}}setChecking(false)});const {data}=supabase.auth.onAuthStateChange(async(_e,s)=>{setSession(s);if(s){try{setProfile(await getProfile())}catch{setProfile(null)}}else setProfile(null)});return()=>data.subscription.unsubscribe()},[]);
 if(checking)return <div className="loading">Loading EduSphere…</div>; if(!session)return <PublicHome/>;
 const role=profile?.role||'student', admin=role==='admin';
 const teacherModules=new Set(['Dashboard','Students','Teachers','Classes','Student Attendance','Teacher Attendance','Fees','Assignments','Assignment Submissions','Exams','Results','Fee Payments','Notices','Reports','About']);
 const allowed=(x:string)=>x==='Dashboard' || x==='About' || admin || (role==='teacher' && teacherModules.has(x)) || (role==='accountant' && ['Fees','Fee Payments','Reports'].includes(x)) || (role==='student' && ['Dashboard','Assignments','Assignment Submissions','Results','Notices'].includes(x)) || (role==='parent' && ['Dashboard','Results','Fees','Notices'].includes(x));
 const signOut=async()=>{await supabase.auth.signOut();setActive('Dashboard')};
 let content:any=<Dashboard/>;
 if(!allowed(active)) content=<section className="page"><div className="card"><h2>Access restricted</h2><p>Your account role (<b>{role}</b>) does not have access to this module.</p></div></section>;
 else if(active==='Students')content=<Students readOnly={!admin}/>; else if(active==='Student Attendance')content=<Attendance admin={admin}/>; else if(active==='Teacher Attendance')content=<Attendance teacher admin={admin}/>; else if(active==='Fees')content=<Fees admin={admin}/>; else if(active==='Assignments')content=<Assignments teacher={role==='teacher'} admin={admin}/>; else if(active==='Assignment Submissions')content=<Submissions teacher={role==='teacher'} admin={admin}/>; else if(active==='Teachers')content=<Teachers readOnly={!admin}/>; else if(active==='Results')content=<Results readOnly={role==='student'||role==='parent'} canDelete={admin}/>; else if(active==='Reports')content=<Reports/>; else if(active==='Settings')content=<Settings admin={admin}/>; else if(active==='About')content=<About/>; else if(active==='Activity Log')content=<ActivityLog/>; else if(pages[active]){const cfg=pages[active];content=<CrudPage canAdd={role==='teacher' && ['Exams','Notices'].includes(active)} title={active} table={cfg.table} order={cfg.order??'created_at'} fields={cfg.fields.map((x:any)=>({key:x[0],label:x[1],type:x[2],required:['full_name','student_code','name','section','academic_year','title'].includes(x[0])}))} readOnly={!admin}/>;}
 return <div className="app"><Sidebar active={active} role={role} onSelect={(x:string)=>x==='Logout'?signOut():setActive(x)}/><main><Header title={active}/><div className="role-badge">Signed in as <b>{profile?.full_name||session.user.email}</b> · <b>{role}</b></div>{content}<Footer/></main></div>}

function PublicHome(){const [login,setLogin]=useState(false); return login?<Login onLogin={()=>window.location.reload()}/>:<Landing onLogin={()=>setLogin(true)}/>}
function About(){return <section className="page"><div className="about-hero"><div><span className="eyebrow">EDUSPHERE</span><h2>Smart School Management. Simple. Connected. Powerful.</h2><p>EduSphere brings students, teachers, attendance, fees, assignments, exams, results and school communication into one modern workspace.</p></div><div className="about-orb">E</div></div><div className="about-grid"><div className="card"><h3>Built & Developed by Hanzala Khan</h3><p className="muted">Turning simple ideas into powerful digital solutions.</p><div className="contact-actions"><a className="primary" href="mailto:hanzala3311211@gmail.com">Email Developer</a><a className="secondary" href="https://wa.me/923467032832" target="_blank" rel="noreferrer">WhatsApp</a></div></div><div className="card"><h3>EduSphere</h3><p className="muted">A practical school operating system designed for fast daily work and shared cloud data.</p><div className="about-lines"><span>✓ Multi-role access</span><span>✓ Cloud database ready</span><span>✓ Responsive on phone, tablet & PC</span><span>✓ Admin-controlled settings</span></div></div></div></section>}
function Footer(){return <footer className="site-footer"><div><b>EduSphere</b><span>Smart School Management</span></div><div className="footer-contact"><span>Developed by <b>Hanzala Khan</b></span><a href="mailto:hanzala3311211@gmail.com">hanzala3311211@gmail.com</a><a href="https://wa.me/923467032832" target="_blank" rel="noreferrer">WhatsApp: 03467032832</a></div></footer>}

function Reports(){return <section className="page"><div className="page-head"><div><h2>Reports</h2><p>Live summaries from your cloud database.</p></div></div><div className="card-grid"><Report table="students" label="Students"/><Report table="teachers" label="Teachers"/><Report table="student_attendance" label="Student attendance"/><Report table="teacher_attendance" label="Teacher attendance"/><Report table="fees" label="Fees"/><Report table="results" label="Results"/></div></section>}
function Report({table,label}:{table:string;label:string}){const [n,setN]=useState(0);useEffect(()=>{import('./lib/api').then(m=>m.rows(table)).then(d=>setN(d.length)).catch(()=>{})},[table]);return <div className="card"><h3>{label}</h3><strong className="big-number">{n}</strong><p>records currently stored</p></div>}
function Settings({admin}:{admin:boolean}){
 const defaults={schoolName:'EduSphere School',schoolPhone:'',schoolEmail:'',schoolAddress:'',principalName:'',academicYear:'2026-27',passingPercentage:'40',attendanceMinimum:'75',feeDueDay:'10',lateFine:'0',currency:'PKR',attendanceLateAfter:'10',feeReminders:true,attendanceAlerts:true,assignmentReminders:true,darkMode:false};
 const [s,setS]=useState<any>(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem('edusphere_settings')||'{}')}}catch{return defaults}});
 const [saved,setSaved]=useState(false); const [tab,setTab]=useState('School');
 if(!admin)return <section className="page"><div className="card"><h2>Access restricted</h2><p>Only the administrator can change school settings.</p></div></section>;
 const set=(k:string,v:any)=>setS((x:any)=>({...x,[k]:v}));
 const save=()=>{localStorage.setItem('edusphere_settings',JSON.stringify(s));document.documentElement.classList.toggle('dark-mode',!!s.darkMode);setSaved(true);setTimeout(()=>setSaved(false),1800)};
 const reset=()=>{localStorage.removeItem('edusphere_settings');setS(defaults);document.documentElement.classList.remove('dark-mode')};
 const tabs=['School','Academic','Fees','Attendance','Notifications','Appearance','Security','Data'];
 return <section className="page"><div className="page-head"><div><h2>Settings</h2><p>Manage EduSphere school configuration and administrator preferences.</p></div><button className="primary" onClick={save}>Save Changes</button></div>
 {saved&&<div className="success">Settings saved successfully.</div>}
 <div className="settings-layout"><div className="settings-tabs">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="card settings-panel">
 {tab==='School'&&<><h3>School Information</h3><p className="muted">Basic information shown across the school system and reports.</p><div className="form-grid"><label>School Name<input value={s.schoolName} onChange={e=>set('schoolName',e.target.value)}/></label><label>Principal / Head<input value={s.principalName} onChange={e=>set('principalName',e.target.value)}/></label><label>Phone<input value={s.schoolPhone} onChange={e=>set('schoolPhone',e.target.value)}/></label><label>Email<input value={s.schoolEmail} onChange={e=>set('schoolEmail',e.target.value)}/></label><label>Address<textarea value={s.schoolAddress} onChange={e=>set('schoolAddress',e.target.value)}/></label></div></>}
 {tab==='Academic'&&<><h3>Academic Settings</h3><p className="muted">Set the active session and result rules.</p><div className="form-grid"><label>Current Academic Year<input value={s.academicYear} onChange={e=>set('academicYear',e.target.value)}/></label><label>Passing Percentage<input type="number" min="0" max="100" value={s.passingPercentage} onChange={e=>set('passingPercentage',e.target.value)}/></label><label>Minimum Attendance %<input type="number" min="0" max="100" value={s.attendanceMinimum} onChange={e=>set('attendanceMinimum',e.target.value)}/></label></div></>}
 {tab==='Fees'&&<><h3>Fee Settings</h3><p className="muted">Defaults used when recording school fees.</p><div className="form-grid"><label>Currency<input value={s.currency} onChange={e=>set('currency',e.target.value)}/></label><label>Fee Due Day<input type="number" min="1" max="31" value={s.feeDueDay} onChange={e=>set('feeDueDay',e.target.value)}/></label><label>Default Late Fine<input type="number" min="0" value={s.lateFine} onChange={e=>set('lateFine',e.target.value)}/></label></div></>}
 {tab==='Attendance'&&<><h3>Attendance Rules</h3><p className="muted">Configure how attendance is interpreted.</p><div className="form-grid"><label>Minimum Attendance %<input type="number" min="0" max="100" value={s.attendanceMinimum} onChange={e=>set('attendanceMinimum',e.target.value)}/></label><label>Late After (minutes)<input type="number" min="0" value={s.attendanceLateAfter} onChange={e=>set('attendanceLateAfter',e.target.value)}/></label></div><div className="settings-note"><b>Statuses:</b> Present · Absent · Leave · Late</div></>}
 {tab==='Notifications'&&<><h3>Notifications</h3><p className="muted">Choose which reminders the school wants to use.</p><div className="setting-toggle"><span><b>Fee reminders</b><small>Remind about unpaid or overdue fees.</small></span><input type="checkbox" checked={s.feeReminders} onChange={e=>set('feeReminders',e.target.checked)}/></div><div className="setting-toggle"><span><b>Attendance alerts</b><small>Flag students with low attendance.</small></span><input type="checkbox" checked={s.attendanceAlerts} onChange={e=>set('attendanceAlerts',e.target.checked)}/></div><div className="setting-toggle"><span><b>Assignment reminders</b><small>Show upcoming assignment reminders.</small></span><input type="checkbox" checked={s.assignmentReminders} onChange={e=>set('assignmentReminders',e.target.checked)}/></div></>}
 {tab==='Appearance'&&<><h3>Appearance</h3><p className="muted">Customize the administrator's local app view.</p><div className="setting-toggle"><span><b>Dark mode</b><small>Use a darker interface on this device.</small></span><input type="checkbox" checked={s.darkMode} onChange={e=>set('darkMode',e.target.checked)}/></div></>}
 {tab==='Security'&&<><h3>Security & Access</h3><p className="muted">Database permissions should remain enforced by Supabase RLS.</p><div className="security-grid"><div><b>Administrator</b><span>Full control</span></div><div><b>Teachers</b><span>Add teaching records; no editing/deleting</span></div><div><b>Accountant</b><span>Fees and payments</span></div><div><b>Student / Parent</b><span>Read-focused access</span></div></div><div className="settings-note">Never place a Supabase service-role or secret key in the frontend.</div></>}
 {tab==='Data'&&<><h3>Data Tools</h3><p className="muted">Useful local tools for this device.</p><div className="settings-actions"><button className="secondary" onClick={()=>{const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='edusphere-settings.json';a.click();URL.revokeObjectURL(a.href)}}>Export Settings</button><button className="secondary" onClick={reset}>Reset Settings</button></div><div className="settings-note">Student, teacher, attendance and fee records remain in your Supabase cloud database. This page only exports the settings stored on this device.</div></>}
 </div></div></section>
}
export default App;